### ISSUE TITLE
won't start scripts

### ISSUE THREAD

**Issue by 8o8b14Ka** [HalfstarDev/matchanovel#2]
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.8.1 (fd1ad4c)
ERROR:DLIB: Failed to initialize profile library 9
INFO:ENGINE: Loading data from: build/default
/dev/shm/jack_db-1000/__db.001: No such file or directory
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: load_script error:	Failed to load resource: /assets/scripts/scripts.txt (-3)
INFO:DLIB: SSDP: Started on address 192.168.0.182
INFO:DLIB: SSDP: Done on address 192.168.0.182

options and main menu works ok. black screen on start

**Comment by HalfstarDev** [comment]
Regarding the load_script error, is the assets folder accessible for the project? Did you put the assets folder in the same folder as game.project? Can you open /assets/scripts/scripts.txt?

Also, the first error you get, ERROR:DLIB, should not come from MatchaNovel, as it does not use dlib, that should be either Defold or another extension. Maybe another error from your project is messing up the IO script. If you reinstall Defold, and open an empty MatchaNovel project, does it still happen? Or only after adding other extensions, code, or assets?

**Comment by 8o8b14Ka** [comment]
just fixed this for myself by modifying matchascript.lua
this line:
`local scripts_folder = "\\assets\\scripts\\"`
into:
`local scripts_folder = "/assets/scripts/"`

maybe consider doing this less os dependent

**Comment by HalfstarDev** [comment]
Oh, yes, I should change that file access to be Unix compatible. Thanks.

**Comment by HalfstarDev** [comment]
Fixed in version v0.2.2.
