### ISSUE TITLE
black screen after start on build HTML5

### ISSUE THREAD

**Issue by 8o8b14Ka** [HalfstarDev/matchanovel#4]
steps to replicate:

- open MatchaNovel on defold 1.9.2
- run Project/Build HTML5
- choose Start on start menu
- - expected:  Chloe on the river, some story
- - got :  Black screen, no story

**Comment by HalfstarDev** [comment]
This should be fixed with the newest commit.

**Comment by 8o8b14Ka** [comment]
Works now, can confirm. Thanks!
