### ISSUE TITLE
White screen after last commit

### ISSUE THREAD

**Issue by 8o8b14Ka** [HalfstarDev/matchanovel#5]
to replicate:
 - on 1.9.2 load
 - F5
 - choose start
 - - expected: Chloe on the river, some story
 - - got 'river' caption on white screen, no story

works as expected if reset to previous commit

**Comment by HalfstarDev** [comment]
This should be fixed with the newest commit.

**Comment by 8o8b14Ka** [comment]
Works now, can confirm. Thanks!
